import "./globals.css";
import "@glimpz-io/ui/styles.css";
import type { Metadata } from "next";
import { GeistSans } from "geist/font";

export const metadata: Metadata = {
    title: "Glimpz - Coming Soon...",
    description: "Generated by create turbo",
};

export default function RootLayout({ children }: { children: React.ReactNode }): JSX.Element {
    return (
        <html lang="en" className="bg-gradient-to-r from-neutral-950 to-zinc-950">
            <body className={GeistSans.className}>{children}</body>
        </html>
    );
}
